# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:6.1.0
COPY types.db /usr/share/collectd/types.db
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
